name: Build DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ['1.21.1']
        arch: ['386', 'amd64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install MinGW
      if: matrix.arch == 'amd64'
      run: choco install mingw --version 13.2.0 --force
    - name: Install MinGW
      if: matrix.arch == '386'
      run: choco install mingw --version 13.2.0 --x86 --force
    - name: Add MinGW to PATH
      if: matrix.arch == '386'
      run: echo "C:\ProgramData\mingw64\mingw32\bin" | Out-File -Append -LiteralPath $env:GITHUB_PATH -Encoding utf8
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        architecture: ${{ matrix.arch }}

    - name: Build DLL
      run: go build -o jsonataxls-${{ matrix.arch }}.dll -buildmode=c-shared .
      env:
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 1

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: jsonataxls-${{ matrix.arch }}.dll
        path: jsonataxls-${{ matrix.arch }}.dll
